spring:
  datasource:
    username: root
    password: 123456!@#$%^
    url: jdbc:mysql://192.168.0.208:3308/hh_transport?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8

  elasticsearch:
    rest:
      password: admin
      username: admin
      uris: http://192.168.0.209:9200


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  #    mapUnderscoreToCamelCase: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



